#!/bin/sh
# Copyright (C) 2000-2016 Synology Inc. All rights reserved.

PACKAGE_NAME=pkgext
PACKAGE_DIR="/var/packages/${PACKAGE_NAME}"
SCRIPTS_DIR="${PACKAGE_DIR}/scripts"


start()
{
	# fix downloadstation settings
	${SCRIPTS_DIR}/fix_downloadstation.sh
}

case $1 in
	start)
		### Start this package.
		start

		exit 0
	;;
	stop)
		### Stop this package.
		exit 0
	;;
	status)
		### Check package alive.
		if [ -h "/usr/bin/pkgext" ]; then
			exit 0
		else
			exit 1
		fi
	;;
	killall)
        ;;
	log)
		exit 0
	;;
esac

